version: "3.8"

services:
  psql-db:
    image: postgres
    container_name: psql-db
    restart: always
    environment:
      - POSTGRES_USER=usrtalentcenter
      - POSTGRES_PASSWORD=m1QVs3zKymgPduz
      - POSTGRES_DB=new_db_talentcenter_dev
    ports:
      - '5545:5545'

  recipe:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://cloudias79.com:5545/new_db_talentcenter_dev
      - SPRING_DATASOURCE_USERNAME=usrtalentcenter
      - SPRING_DATASOURCE_PASSWORD=m1QVs3zKymgPduz
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
    depends_on:
      - psql-db